// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUSpJa09sUkSIyMBrjqwh7M1Z0x-Ogw8',
    appId: '1:691777521155:web:a2698a7f2f54a89b87b036',
    messagingSenderId: '691777521155',
    projectId: 'trashiq-ba129',
    authDomain: 'trashiq-ba129.firebaseapp.com',
    storageBucket: 'trashiq-ba129.firebasestorage.app',
    measurementId: 'G-B88ECBSQSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB12yriGXP56cEybFYXYNCoIRqKpgS1Bjc',
    appId: '1:691777521155:android:662b22d1da9a226787b036',
    messagingSenderId: '691777521155',
    projectId: 'trashiq-ba129',
    storageBucket: 'trashiq-ba129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvpbLsBTGtfVIBcOvThh9gk-3Q5xm_taI',
    appId: '1:691777521155:ios:ab3dad2a0eb4fa7a87b036',
    messagingSenderId: '691777521155',
    projectId: 'trashiq-ba129',
    storageBucket: 'trashiq-ba129.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvpbLsBTGtfVIBcOvThh9gk-3Q5xm_taI',
    appId: '1:691777521155:ios:ab3dad2a0eb4fa7a87b036',
    messagingSenderId: '691777521155',
    projectId: 'trashiq-ba129',
    storageBucket: 'trashiq-ba129.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADUSpJa09sUkSIyMBrjqwh7M1Z0x-Ogw8',
    appId: '1:691777521155:web:46ab30f4977a8f6b87b036',
    messagingSenderId: '691777521155',
    projectId: 'trashiq-ba129',
    authDomain: 'trashiq-ba129.firebaseapp.com',
    storageBucket: 'trashiq-ba129.firebasestorage.app',
    measurementId: 'G-T30PWLJNX6',
  );
}
